import * as vm from './viewModel';

export const mockCourses: vm.Course[] = [
  {
    name: 'Primer curso',
    subjects: [
      {
        id: '1',
        name: '1º DERECHO DE LA EMPRESA',
        quarter: 'Primer cuatrimestre',
        credits: '1.00',
        isSelected: false,
        group: 'Grupo A',
        time: 'Mañana',
        teacher: 'Antonio Rodriguez',
      },
    ],
  },
  {
    name: 'Segundo curso',
    subjects: [
      {
        id: '1',
        name: '2º DERECHO DE LA EMPRESA',
        quarter: 'Primer cuatrimestre',
        credits: '2.00',
        isSelected: false,
        group: 'Grupo B',
        time: 'Mañana',
        teacher: 'Antonio Rodriguez',
      },
      {
        id: '2',
        name: '2º ECONOMIA',
        quarter: 'Segundo cuatrimestre',
        credits: '3.00',
        isSelected: false,
        group: 'Grupo C',
        time: 'Tarde',
        teacher: 'Francisco Martinez',
      },
    ],
  },
  {
    name: 'Tercer curso',
    subjects: [
      {
        id: '1',
        name: '3º DERECHO DE LA EMPRESA',
        quarter: 'Primer cuatrimestre',
        credits: '1.00',
        isSelected: false,
        group: 'Grupo B',
        time: 'Mañana',
        teacher: 'Sara López Núñez',
      },
      {
        id: '2',
        name: '3º ECONOMIA',
        quarter: 'Segundo cuatrimestre',
        credits: '2.00',
        isSelected: false,
        group: 'Grupo C',
        time: 'Tarde',
        teacher: 'Francisco Martinez',
      },
      {
        id: '3',
        name: '3º FUNDAMENTOS DE DIRECCIÓN DE EMPRESAS',
        quarter: 'Segundo cuatrimestre',
        credits: '3.00',
        isSelected: false,
        group: 'Grupo D',
        time: 'Tarde',
        teacher: 'Manuel Perez',
      },
    ],
  },
  {
    name: 'Cuarto curso',
    subjects: [
      {
        id: '1',
        name: '4º DERECHO DE LA EMPRESA',
        quarter: 'Primer cuatrimestre',
        credits: '1.00',
        isSelected: false,
        group: 'Grupo A',
        time: 'Mañana',
        teacher: 'Maria Perez',
      },
      {
        id: '2',
        name: '4º ECONOMIA',
        quarter: 'Primero cuatrimestre',
        credits: '2.00',
        isSelected: false,
        group: 'Grupo B',
        time: 'Tarde',
        teacher: 'Paco Aguilar',
      },
      {
        id: '3',
        name: '4º FUNDAMENTOS DE DIRECCIÓN DE EMPRESAS',
        quarter: 'Segundo cuatrimestre',
        credits: '3.00',
        isSelected: false,
        group: 'Grupo C',
        time: 'Tarde',
        teacher: 'Sandra Naranjo',
      },
      {
        id: '4',
        name: '4º DISEÑO',
        quarter: 'Segundo cuatrimestre',
        credits: '4.00',
        isSelected: false,
        group: 'Grupo D',
        time: 'Mañana',
        teacher: 'Manuel Perez',
      },
    ],
  },
  {
    name: 'Asignaturas optativas de carácter general',
    subjects: [
      {
        id: '1',
        name: 'Optativa 1',
        quarter: 'Primer cuatrimestre',
        credits: '5.00',
        isSelected: false,
        group: 'Grupo D',
        time: 'Tarde',
        teacher: 'Enrqiue Rodriguez',
      },
    ],
  },
];
