version: 2
jobs:
  build:
    working_directory: ~/lab-ocu
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - run:
          name: test
          command: 'npm test'
